### PR TITLE
Fix variant reading into intron

### LINKED ISSUE #82: Exception when deletion extends beyond exon boundary
@iskandr commented on [Sun May 14 2017](https://github.com/hammerlab/varcode/issues/224)

```ValueError: Wrong reference sequence for variant Variant(contig='11', start=106262686, ref='GTGAAGG', alt='', reference_name='GRCm38') on transcript Transcript(transcript_id=ENSMUST00000021049, name=Psmc5-001, gene_id=ENSMUSG00000020708, gene_name=Psmc5, biotype=protein_coding, location=11:106256154-106263120)
```

The end of exon 9 is “GTGAAG” and the next intronic nt is “G”. So the variant deletes the end of the exon and the next nucleotide. Varcode only looks at the transcript sequence and apparently doesn’t clip the variant to only cover the exons. (This seems like it would likely cause a splice variant, since both the exonic and intronic splice signal is potentially damaged).

---

@ihodes commented on [Tue May 16 2017](https://github.com/hammerlab/varcode/issues/224#issuecomment-301862801)

What is the right thing to do here? 

---

@julia326 commented on [Wed May 17 2017](https://github.com/hammerlab/varcode/issues/224#issuecomment-302231165)

Example where this comes up:
ValueError: Wrong reference sequence for variant Variant(contig='11', start=106262686, ref='GTGAAGG', alt='', reference_name='GRCm38') on transcript Transcript(transcript_id=ENSMUST00000021049, name=Psmc5-001, gene_id=ENSMUSG00000020708, gene_name=Psmc5, biotype=protein_coding, location=11:106256154-106263120)

---

@julia326 commented on [Mon May 22 2017](https://github.com/hammerlab/varcode/issues/224#issuecomment-303241235)

Went over this with @iskandr. Varcode is doing the right thing and, when predicting the effect, trimming the variant to just the exon, but it's not altering the variant object itself - and isovar replicated the "does the reference match" check but didn't account for a variant reading into the intron. Solution: 1) remove that isovar check, 2) add a logging statement to varcode if it trims the variant like that and make sure it gets logged. Doing that shortly...

### PR DESCRIPTION
**Pull request by julia326**
Fixes #82

---
This change is [Reviewable](https://reviewable.io/reviews/hammerlab/isovar/83)

### CODE REVIEW

File: lint.sh [hunk 1]
```diff
@@ -10,6 +10,6 @@ set -o errexit
 find . -name '*.py' \
   | xargs pylint \
   --errors-only \
-  --disable=print-statement,unsubscriptable-object,not-an-iterable,no-member
+  --disable=print-statement,unsubscriptable-object,not-an-iterable,no-member,invalid-unary-operand-type
```
Comment (iskandr) [inline lint.sh]: Ha, where did this error pop up?

File: test/test_reference_sequence_key.py [hunk 2]
```diff
@@ -199,3 +199,15 @@ def test_reference_sequence_key_hash_and_equality_different_objects():
...
+    # variant reads into the intron; want to make sure isovar skips over such cases
+    mouse_genome = genome_for_reference_name("grcm38")
+    variant = Variant(
+        "11", 106262686, "GTGAAGG", "", mouse_genome)
+    transcript = mouse_genome.transcript_by_id("ENSMUST00000021049")
+    sequence_key = ReferenceSequenceKey.from_variant_and_transcript(
+        variant=variant,
+        transcript=transcript,
+        context_size=10)
+    assert sequence_key == None, '%s\n%s' % (sequence_key, transcript)
```
Comment (iskandr) [inline test/test_reference_sequence_key.py]: Nit: Use `is` for comparing to `None` (https://www.python.org/dev/peps/pep-0008/#programming-recommendations)

File: lint.sh (hunk 1 above)
Comment (julia326) [inline lint.sh]: in isovar.read_helpers line 59 :)
